version: '3'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "8080:8080"
      - "4567-4592:4567-4592"
    environment:
      - SERVICES=s3,sts
