version: '3'

services:
  example-app:
    build:
      context: ../..
      dockerfile: ${PWD}/Dockerfile
    depends_on:
      - localstack-app-demo
  localstack-app-demo:
    container_name: localstack-app-demo
    image: localstack/localstack
    environment:
      - SERVICES=s3,sts
